### ISSUE TITLE
PHPUnit made `\PHPUnit\TextUI\TestRunner` final

### ISSUE THREAD

**Issue by spawnia** [wizacode/phpunit-slicer#7]
Since PHPUnit made this class `final`, we should look for another way of hooking into its functionality.

I hacked together a quick fix for now by just copy-and-pasting the contents of the class, but there has to be a better way to achieve this.

**Comment by spawnia** [comment]
This should be resolved by https://github.com/wizacode/phpunit-slicer/pull/13.

Thank you @ecourtial for merging the fix and creating a new release. Would you mind creating another release with the proper semantic version number `1.0.0` (the current release is `1.0` and thus missing a segment).

**Comment by ecourtial** [comment]
@spawnia Done :)
